# Generated by Django 5.1.6 on 2025-04-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credit_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.invoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.party')),
            ],
        ),
    ]
