# Generated by Django 5.1.6 on 2025-04-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='credit_amount',
            new_name='pending_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='debit_amount',
            new_name='received_amount',
        ),
    ]
